#pin constraints
set_property PACKAGE_PIN AR26 [get_ports pin_reset_n]
set_property PACKAGE_PIN AY23 [get_ports pin_sys_clk_p]
set_property PACKAGE_PIN BA23 [get_ports pin_sys_clk_n]
set_property PACKAGE_PIN AP11 [get_ports pin_pcie_ref_clk_p]
set_property PACKAGE_PIN AP10 [get_ports pin_pcie_ref_clk_n]
set_property PACKAGE_PIN BF23 [get_ports bmc2fpga_i2c_sda]
set_property PACKAGE_PIN BF24 [get_ports bmc2fpga_i2c_scl]
set_property PACKAGE_PIN AV22 [get_ports i2c_fpga_m_scl]
set_property PACKAGE_PIN BF22 [get_ports i2c_fpga_m_sda]
set_property PACKAGE_PIN BE8 [get_ports mac_scl]
set_property PACKAGE_PIN BF9 [get_ports mac_sda]
set_property PACKAGE_PIN BF7 [get_ports sta_secure_scl]
set_property PACKAGE_PIN BE7 [get_ports sta_secure_sda]
set_property PACKAGE_PIN D14 [get_ports dync_secure_scl]
set_property PACKAGE_PIN C17 [get_ports dync_secure_sda]
set_property PACKAGE_PIN BF8 [get_ports rst_sec_sta]
set_property PACKAGE_PIN L15 [get_ports rst_sec_dync]
set_property PACKAGE_PIN AM24 [get_ports fpga_mcu_rsv_dri]


set_property PACKAGE_PIN AP23 [get_ports program_inband]
set_property PACKAGE_PIN BF10 [get_ports mac_wp]
set_property PACKAGE_PIN BD23 [get_ports fpga_act]
#
###########################################################################
#########################################
set_property IOSTANDARD LVCMOS12 [get_ports pin_reset_n]
set_property IOSTANDARD LVCMOS18 [get_ports bmc2fpga_i2c_sda]
set_property IOSTANDARD LVCMOS18 [get_ports bmc2fpga_i2c_scl]
set_property IOSTANDARD LVCMOS18 [get_ports i2c_fpga_m_scl]
set_property IOSTANDARD LVCMOS18 [get_ports i2c_fpga_m_sda]
set_property IOSTANDARD LVCMOS18 [get_ports mac_scl]
set_property IOSTANDARD LVCMOS18 [get_ports mac_sda]
set_property IOSTANDARD LVCMOS18 [get_ports sta_secure_scl]
set_property IOSTANDARD LVCMOS18 [get_ports sta_secure_sda]
set_property IOSTANDARD LVCMOS12 [get_ports dync_secure_scl]
set_property IOSTANDARD LVCMOS12 [get_ports dync_secure_sda]
set_property IOSTANDARD LVCMOS12 [get_ports rst_sec_dync]
set_property IOSTANDARD LVCMOS18 [get_ports rst_sec_sta]
set_property IOSTANDARD LVCMOS18 [get_ports fpga_mcu_rsv_dri]
set_property IOSTANDARD LVCMOS18 [get_ports program_inband]
set_property IOSTANDARD LVCMOS18 [get_ports mac_wp]
set_property IOSTANDARD LVCMOS18 [get_ports fpga_act]
set_property DRIVE 8 [get_ports dync_secure_sda]
set_property IOSTANDARD LVDS [get_ports pin_sys_clk_p]
set_property IOSTANDARD LVDS [get_ports pin_sys_clk_n]
set_property PACKAGE_PIN BD24 [get_ports qsfp28a_lpmode]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp28a_lpmode]
set_property PACKAGE_PIN AU24 [get_ports qsfp28b_lpmode]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp28b_lpmode]
set_property PACKAGE_PIN AT22 [get_ports qsfp28a_rst]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp28a_rst]

set_property PACKAGE_PIN AR22 [get_ports qsfp28b_rst]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp28b_rst]
set_property PACKAGE_PIN AL21 [get_ports qsfp28b_act_link]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp28b_act_link]
set_property PACKAGE_PIN AL24 [get_ports qsfp28a_act_link]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp28a_act_link]
set_property PACKAGE_PIN AM22 [get_ports globle_reset_n]
set_property IOSTANDARD LVCMOS18 [get_ports globle_reset_n]
set_property PACKAGE_PIN AT24 [get_ports mem_event]
set_property IOSTANDARD LVCMOS18 [get_ports mem_event]
set_property PACKAGE_PIN BE22 [get_ports qsfp28a_prsnt]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp28a_prsnt]
set_property PACKAGE_PIN BE21 [get_ports qsfp28b_prsnt]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp28b_prsnt]
set_property PACKAGE_PIN BC9 [get_ports mcu_fpga_rsv]
set_property IOSTANDARD LVCMOS18 [get_ports mcu_fpga_rsv]
###########################################################################
###########################################
#timing constraints
#sys ref clk 100M
create_clock -period 10.000 -name pin_sys_clk_p [get_ports pin_sys_clk_p]
# pcie x8 ref clk 100M
create_clock -period 10.000 -name pin_pcie_ref_clk_p [get_ports pin_pcie_ref_clk_p]
create_generated_clock -name mmcm_sysclk_out0 [get_pins u_clkm_top/u_clkm/
u_mmcm_sys/inst/mmcme3_adv_inst/CLKOUT0]
###########################################################################
###########################################
set_clock_groups -asynchronous -group [get_clocks pin_sys_clk_p]
set_clock_groups -asynchronous -group [get_clocks mmcm_sysclk_out0]
set_false_path -from [get_clocks pin_pcie_ref_clk_p] -to [get_clocks mmcm_sysclk_out0]

set_false_path -from [get_clocks -of_objects [get_pins u_pcie_top_x16/u_pcie_ep_top_16x/
u_pcie_ep/inst/gt_top_i/diablo_gt.diablo_gt_phy_wrapper/phy_clk_i/bufg_gt_userclk/O]] -to
[get_clocks mmcm_sysclk_out0]
###########################################################################
###########################################
#jitter constraints
set_input_jitter pin_pcie_ref_clk_p 0.100
###########################################################################
###########################################
#bitstream gen cfg for spi interface
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 21.3 [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.TIMER_CFG 0x00050000 [current_design]
set_property BITSTREAM.CONFIG.NEXT_CONFIG_REBOOT ENABLE [current_design]
set_property BITSTREAM.CONFIG.NEXT_CONFIG_ADDR 0x01800000 [current_design]
###########################################################################
###########################################
set_max_delay -datapath_only -from [get_cells -hier *spi_sck_reg] -to [get_pins -hier
*STARTUP*_inst/USRCCLKO] 2.000
set_max_delay -datapath_only -from [get_cells -hier *spi_mosi_reg] -to [get_pins -hier
*STARTUP*_inst/DO[0]] 2.000
set_max_delay -datapath_only -from [get_pins -hier *STARTUP*_inst/DI[1]] -to [get_cells -
hier *rx_data_buf_sft_reg[0]] 2.000
###########################################################################
#########
# The end Constraints from file
###########################################################################
#########
B.2 DDR Constraints
#DDR_a
set_property PACKAGE_PIN W34 [get_ports {ddra_72b_dq[59]}]
set_property PACKAGE_PIN W33 [get_ports {ddra_72b_dq[58]}]

set_property PACKAGE_PIN Y33 [get_ports {ddra_72b_dq[57]}]
set_property PACKAGE_PIN Y32 [get_ports {ddra_72b_dq[56]}]
set_property PACKAGE_PIN W31 [get_ports {ddra_72b_dqs_t[7]}]
set_property PACKAGE_PIN Y31 [get_ports {ddra_72b_dqs_c[7]}]
set_property PACKAGE_PIN Y30 [get_ports {ddra_72b_dq[61]}]
set_property PACKAGE_PIN W30 [get_ports {ddra_72b_dq[60]}]
set_property PACKAGE_PIN AB34 [get_ports {ddra_72b_dq[62]}]
set_property PACKAGE_PIN AA34 [get_ports {ddra_72b_dq[63]}]
set_property PACKAGE_PIN AA32 [get_ports {ddra_72b_dm_dbi_n[7]}]
set_property PACKAGE_PIN AD34 [get_ports {ddra_72b_dq[42]}]
set_property PACKAGE_PIN AC34 [get_ports {ddra_72b_dq[43]}]
set_property PACKAGE_PIN AC33 [get_ports {ddra_72b_dq[41]}]
set_property PACKAGE_PIN AC32 [get_ports {ddra_72b_dq[40]}]
set_property PACKAGE_PIN AC31 [get_ports {ddra_72b_dqs_t[5]}]
set_property PACKAGE_PIN AD31 [get_ports {ddra_72b_dqs_c[5]}]
set_property PACKAGE_PIN AF30 [get_ports {ddra_72b_dq[44]}]
set_property PACKAGE_PIN AE30 [get_ports {ddra_72b_dq[45]}]
set_property PACKAGE_PIN AE33 [get_ports {ddra_72b_dq[47]}]
set_property PACKAGE_PIN AD33 [get_ports {ddra_72b_dq[46]}]
set_property PACKAGE_PIN AE31 [get_ports {ddra_72b_dm_dbi_n[5]}]
set_property PACKAGE_PIN AF33 [get_ports {ddra_72b_dq[9]}]
set_property PACKAGE_PIN AF32 [get_ports {ddra_72b_dq[8]}]
set_property PACKAGE_PIN AG32 [get_ports {ddra_72b_dq[10]}]
set_property PACKAGE_PIN AG31 [get_ports {ddra_72b_dq[11]}]
set_property PACKAGE_PIN AH31 [get_ports {ddra_72b_dqs_t[1]}]
set_property PACKAGE_PIN AH32 [get_ports {ddra_72b_dqs_c[1]}]
set_property PACKAGE_PIN AG34 [get_ports {ddra_72b_dq[13]}]
set_property PACKAGE_PIN AF34 [get_ports {ddra_72b_dq[12]}]
set_property PACKAGE_PIN AJ33 [get_ports {ddra_72b_dq[14]}]
set_property PACKAGE_PIN AH33 [get_ports {ddra_72b_dq[15]}]
set_property PACKAGE_PIN AH34 [get_ports {ddra_72b_dm_dbi_n[1]}]
set_property PACKAGE_PIN AK31 [get_ports {ddra_72b_dq[33]}]
set_property PACKAGE_PIN AJ31 [get_ports {ddra_72b_dq[32]}]

set_property PACKAGE_PIN AG30 [get_ports {ddra_72b_dq[35]}]
set_property PACKAGE_PIN AG29 [get_ports {ddra_72b_dq[34]}]
set_property PACKAGE_PIN AH28 [get_ports {ddra_72b_dqs_t[4]}]
set_property PACKAGE_PIN AH29 [get_ports {ddra_72b_dqs_c[4]}]
set_property PACKAGE_PIN AJ30 [get_ports {ddra_72b_dq[37]}]
set_property PACKAGE_PIN AJ29 [get_ports {ddra_72b_dq[36]}]
set_property PACKAGE_PIN AK28 [get_ports {ddra_72b_dq[38]}]
set_property PACKAGE_PIN AJ28 [get_ports {ddra_72b_dq[39]}]
set_property PACKAGE_PIN AJ27 [get_ports {ddra_72b_dm_dbi_n[4]}]
set_property PACKAGE_PIN AM34 [get_ports {ddra_72b_dq[0]}]
set_property PACKAGE_PIN AL34 [get_ports {ddra_72b_dq[1]}]
set_property PACKAGE_PIN AM32 [get_ports {ddra_72b_dq[3]}]
set_property PACKAGE_PIN AL32 [get_ports {ddra_72b_dq[2]}]
set_property PACKAGE_PIN AN32 [get_ports {ddra_72b_dqs_t[0]}]
set_property PACKAGE_PIN AN33 [get_ports {ddra_72b_dqs_c[0]}]
set_property PACKAGE_PIN AP34 [get_ports {ddra_72b_dq[4]}]
set_property PACKAGE_PIN AN34 [get_ports {ddra_72b_dq[5]}]
set_property PACKAGE_PIN AR33 [get_ports {ddra_72b_dq[7]}]
set_property PACKAGE_PIN AP33 [get_ports {ddra_72b_dq[6]}]
set_property PACKAGE_PIN AT33 [get_ports {ddra_72b_dm_dbi_n[0]}]
set_property PACKAGE_PIN AW33 [get_ports {ddra_72b_addr[10]}]
set_property PACKAGE_PIN AV33 [get_ports {ddra_72b_addr[14]}]
set_property PACKAGE_PIN AW34 [get_ports {ddra_72b_addr[12]}]
set_property PACKAGE_PIN AV34 [get_ports {ddra_72b_ba[1]}]
set_property PACKAGE_PIN AW36 [get_ports {ddra_72b_addr[8]}]
set_property PACKAGE_PIN AW35 [get_ports {ddra_72b_addr[5]}]
#set_property??? PACKAGE_PIN???? BA33?[get_ports? {ddra_72b_addr[17]}]
set_property PACKAGE_PIN AY33 [get_ports {ddra_72b_cs_n[0]}]
set_property PACKAGE_PIN AY36 [get_ports {ddra_72b_addr[6]}]
set_property PACKAGE_PIN AY35 [get_ports {ddra_72b_addr[3]}]
set_property PACKAGE_PIN BB34 [get_ports {ddra_72b_odt[1]}]
set_property PACKAGE_PIN BA34 [get_ports {ddra_72b_addr[13]}]
set_property PACKAGE_PIN BA35 [get_ports ddra_100m_ref_clk_p]

set_property PACKAGE_PIN BB35 [get_ports ddra_100m_ref_clk_n]
set_property PACKAGE_PIN BC36 [get_ports {ddra_72b_odt[0]}]
set_property PACKAGE_PIN BB36 [get_ports {ddra_72b_addr[1]}]
set_property PACKAGE_PIN BB37 [get_ports ddra_72b_ck_t]
set_property PACKAGE_PIN BC37 [get_ports ddra_72b_ck_c]
set_property PACKAGE_PIN BE36 [get_ports {ddra_72b_addr[0]}]
set_property PACKAGE_PIN BD36 [get_ports ddra_72b_par]
set_property PACKAGE_PIN BE35 [get_ports {ddra_72b_ba[0]}]
set_property PACKAGE_PIN BD35 [get_ports {ddra_72b_addr[16]}]
set_property PACKAGE_PIN BD34 [get_ports {ddra_72b_addr[15]}]
set_property PACKAGE_PIN BC34 [get_ports {ddra_72b_cs_n[1]}]
set_property PACKAGE_PIN BC38 [get_ports {ddra_72b_addr[9]}]
set_property PACKAGE_PIN BB38 [get_ports {ddra_72b_bg[1]}]
set_property PACKAGE_PIN BD39 [get_ports ddra_72b_rst_n]
set_property PACKAGE_PIN BC39 [get_ports ddra_72b_act_n]
set_property PACKAGE_PIN BE40 [get_ports {ddra_72b_addr[11]}]
set_property PACKAGE_PIN BD40 [get_ports {ddra_72b_bg[0]}]
set_property PACKAGE_PIN BF37 [get_ports {ddra_72b_addr[4]}]
set_property PACKAGE_PIN BE37 [get_ports {ddra_72b_addr[2]}]
#set_property??? PACKAGE_PIN???? BF38?[get_ports? {ddra_72b_alert}]
set_property PACKAGE_PIN BE38 [get_ports {ddra_72b_addr[7]}]
set_property PACKAGE_PIN BF40 [get_ports {ddra_72b_cke[0]}]
set_property PACKAGE_PIN BF39 [get_ports {ddra_72b_cke[1]}]
set_property PACKAGE_PIN AL30 [get_ports {ddra_72b_dq[50]}]
set_property PACKAGE_PIN AL29 [get_ports {ddra_72b_dq[49]}]
set_property PACKAGE_PIN AN31 [get_ports {ddra_72b_dq[48]}]
set_property PACKAGE_PIN AM31 [get_ports {ddra_72b_dq[51]}]
set_property PACKAGE_PIN AM29 [get_ports {ddra_72b_dqs_t[6]}]
set_property PACKAGE_PIN AM30 [get_ports {ddra_72b_dqs_c[6]}]
set_property PACKAGE_PIN AP29 [get_ports {ddra_72b_dq[54]}]
set_property PACKAGE_PIN AN29 [get_ports {ddra_72b_dq[55]}]
set_property PACKAGE_PIN AR30 [get_ports {ddra_72b_dq[53]}]
set_property PACKAGE_PIN AP30 [get_ports {ddra_72b_dq[52]}]

set_property PACKAGE_PIN AP31 [get_ports {ddra_72b_dm_dbi_n[6]}]
set_property PACKAGE_PIN AT30 [get_ports {ddra_72b_dq[19]}]
set_property PACKAGE_PIN AT29 [get_ports {ddra_72b_dq[18]}]
set_property PACKAGE_PIN AU31 [get_ports {ddra_72b_dq[17]}]
set_property PACKAGE_PIN AU30 [get_ports {ddra_72b_dq[16]}]
set_property PACKAGE_PIN AU29 [get_ports {ddra_72b_dqs_t[2]}]
set_property PACKAGE_PIN AV29 [get_ports {ddra_72b_dqs_c[2]}]
set_property PACKAGE_PIN AV32 [get_ports {ddra_72b_dq[20]}]
set_property PACKAGE_PIN AU32 [get_ports {ddra_72b_dq[21]}]
set_property PACKAGE_PIN AW31 [get_ports {ddra_72b_dq[22]}]
set_property PACKAGE_PIN AV31 [get_ports {ddra_72b_dq[23]}]
set_property PACKAGE_PIN AW29 [get_ports {ddra_72b_dm_dbi_n[2]}]
set_property PACKAGE_PIN AY32 [get_ports {ddra_72b_dq[25]}]
set_property PACKAGE_PIN AY31 [get_ports {ddra_72b_dq[24]}]
set_property PACKAGE_PIN BA30 [get_ports {ddra_72b_dq[26]}]
set_property PACKAGE_PIN AY30 [get_ports {ddra_72b_dq[27]}]
set_property PACKAGE_PIN BA32 [get_ports {ddra_72b_dqs_t[3]}]
set_property PACKAGE_PIN BB32 [get_ports {ddra_72b_dqs_c[3]}]
set_property PACKAGE_PIN BB29 [get_ports {ddra_72b_dq[31]}]
set_property PACKAGE_PIN BA29 [get_ports {ddra_72b_dq[29]}]
set_property PACKAGE_PIN BB31 [get_ports {ddra_72b_dq[28]}]
set_property PACKAGE_PIN BB30 [get_ports {ddra_72b_dq[30]}]
set_property PACKAGE_PIN BC31 [get_ports {ddra_72b_dm_dbi_n[3]}]
set_property PACKAGE_PIN BD29 [get_ports {ddra_72b_dq[66]}]
set_property PACKAGE_PIN BC29 [get_ports {ddra_72b_dq[67]}]
set_property PACKAGE_PIN BE33 [get_ports {ddra_72b_dq[64]}]
set_property PACKAGE_PIN BD33 [get_ports {ddra_72b_dq[65]}]
set_property PACKAGE_PIN BD30 [get_ports {ddra_72b_dqs_t[8]}]
set_property PACKAGE_PIN BD31 [get_ports {ddra_72b_dqs_c[8]}]
set_property PACKAGE_PIN BF30 [get_ports {ddra_72b_dq[70]}]
set_property PACKAGE_PIN BE30 [get_ports {ddra_72b_dq[71]}]
set_property PACKAGE_PIN BE32 [get_ports {ddra_72b_dq[68]}]
set_property PACKAGE_PIN BE31 [get_ports {ddra_72b_dq[69]}]

set_property PACKAGE_PIN BF32 [get_ports {ddra_72b_dm_dbi_n[8]}]
#DDR_b
set_property PACKAGE_PIN A30 [get_ports {ddrb_72b_dq[34]}]
set_property PACKAGE_PIN B30 [get_ports {ddrb_72b_dq[35]}]
set_property PACKAGE_PIN A29 [get_ports {ddrb_72b_dq[33]}]
set_property PACKAGE_PIN B29 [get_ports {ddrb_72b_dq[32]}]
set_property PACKAGE_PIN A28 [get_ports {ddrb_72b_dqs_c[4]}]
set_property PACKAGE_PIN A27 [get_ports {ddrb_72b_dqs_t[4]}]
set_property PACKAGE_PIN D30 [get_ports {ddrb_72b_dq[37]}]
set_property PACKAGE_PIN E30 [get_ports {ddrb_72b_dq[36]}]
set_property PACKAGE_PIN C29 [get_ports {ddrb_72b_dq[38]}]
set_property PACKAGE_PIN D29 [get_ports {ddrb_72b_dq[39]}]
set_property PACKAGE_PIN C27 [get_ports {ddrb_72b_dm_dbi_n[4]}]
set_property PACKAGE_PIN D28 [get_ports {ddrb_72b_dq[17]}]
set_property PACKAGE_PIN E28 [get_ports {ddrb_72b_dq[16]}]
set_property PACKAGE_PIN E27 [get_ports {ddrb_72b_dq[18]}]
set_property PACKAGE_PIN F27 [get_ports {ddrb_72b_dq[19]}]
set_property PACKAGE_PIN F29 [get_ports {ddrb_72b_dqs_c[2]}]
set_property PACKAGE_PIN F28 [get_ports {ddrb_72b_dqs_t[2]}]
set_property PACKAGE_PIN G29 [get_ports {ddrb_72b_dq[20]}]
set_property PACKAGE_PIN H29 [get_ports {ddrb_72b_dq[21]}]
set_property PACKAGE_PIN G27 [get_ports {ddrb_72b_dq[23]}]
set_property PACKAGE_PIN G26 [get_ports {ddrb_72b_dq[22]}]
set_property PACKAGE_PIN J26 [get_ports {ddrb_72b_dm_dbi_n[2]}]
set_property PACKAGE_PIN J29 [get_ports {ddrb_72b_dq[43]}]
set_property PACKAGE_PIN J28 [get_ports {ddrb_72b_dq[41]}]
set_property PACKAGE_PIN H28 [get_ports {ddrb_72b_dq[42]}]
set_property PACKAGE_PIN H27 [get_ports {ddrb_72b_dq[40]}]
set_property PACKAGE_PIN K27 [get_ports {ddrb_72b_dqs_c[5]}]
set_property PACKAGE_PIN K26 [get_ports {ddrb_72b_dqs_t[5]}]
set_property PACKAGE_PIN L27 [get_ports {ddrb_72b_dq[47]}]
set_property PACKAGE_PIN M27 [get_ports {ddrb_72b_dq[46]}]
set_property PACKAGE_PIN K28 [get_ports {ddrb_72b_dq[45]}]

set_property PACKAGE_PIN L28 [get_ports {ddrb_72b_dq[44]}]
set_property PACKAGE_PIN M29 [get_ports {ddrb_72b_dm_dbi_n[5]}]
set_property PACKAGE_PIN N26 [get_ports {ddrb_72b_dq[48]}]
set_property PACKAGE_PIN P26 [get_ports {ddrb_72b_dq[49]}]
set_property PACKAGE_PIN N28 [get_ports {ddrb_72b_dq[51]}]
set_property PACKAGE_PIN P28 [get_ports {ddrb_72b_dq[50]}]
set_property PACKAGE_PIN N29 [get_ports {ddrb_72b_dqs_c[6]}]
set_property PACKAGE_PIN P29 [get_ports {ddrb_72b_dqs_t[6]}]
set_property PACKAGE_PIN R26 [get_ports {ddrb_72b_dq[53]}]
set_property PACKAGE_PIN T26 [get_ports {ddrb_72b_dq[54]}]
set_property PACKAGE_PIN R27 [get_ports {ddrb_72b_dq[52]}]
set_property PACKAGE_PIN T27 [get_ports {ddrb_72b_dq[55]}]
set_property PACKAGE_PIN T28 [get_ports {ddrb_72b_dm_dbi_n[6]}]
set_property PACKAGE_PIN C31 [get_ports {ddrb_72b_dq[66]}]
set_property PACKAGE_PIN D31 [get_ports {ddrb_72b_dq[67]}]
set_property PACKAGE_PIN B32 [get_ports {ddrb_72b_dq[64]}]
set_property PACKAGE_PIN C32 [get_ports {ddrb_72b_dq[65]}]
set_property PACKAGE_PIN A33 [get_ports {ddrb_72b_dqs_c[8]}]
set_property PACKAGE_PIN A32 [get_ports {ddrb_72b_dqs_t[8]}]
set_property PACKAGE_PIN C33 [get_ports {ddrb_72b_dq[69]}]
set_property PACKAGE_PIN D33 [get_ports {ddrb_72b_dq[70]}]
set_property PACKAGE_PIN C34 [get_ports {ddrb_72b_dq[68]}]
set_property PACKAGE_PIN D34 [get_ports {ddrb_72b_dq[71]}]
set_property PACKAGE_PIN B34 [get_ports {ddrb_72b_dm_dbi_n[8]}]
set_property PACKAGE_PIN D35 [get_ports {ddrb_72b_addr[14]}]
set_property PACKAGE_PIN E35 [get_ports {ddrb_72b_par}]
set_property PACKAGE_PIN A35 [get_ports {ddrb_72b_addr[15]}]
set_property PACKAGE_PIN B35 [get_ports {ddrb_72b_addr[10]}]
set_property PACKAGE_PIN B37 [get_ports {ddrb_72b_addr[4]}]
set_property PACKAGE_PIN B36 [get_ports {ddrb_72b_addr[16]}]
set_property PACKAGE_PIN A38 [get_ports {ddrb_72b_addr[3]}]
set_property PACKAGE_PIN A37 [get_ports {ddrb_72b_ba[0]}]
set_property PACKAGE_PIN D36 [get_ports {ddrb_72b_odt[0]}]

set_property PACKAGE_PIN E36 [get_ports {ddrb_72b_ba[1]}]
set_property PACKAGE_PIN C37 [get_ports {ddrb_72b_cs_n[0]}]
set_property PACKAGE_PIN C36 [get_ports {ddrb_72b_addr[0]}]
set_property PACKAGE_PIN C39 [get_ports {ddrb_100m_ref_clk_n}]
set_property PACKAGE_PIN C38 [get_ports {ddrb_100m_ref_clk_p}]
set_property PACKAGE_PIN D38 [get_ports {ddrb_72b_addr[6]}]
set_property PACKAGE_PIN E38 [get_ports {ddrb_72b_bg[1]}]
set_property PACKAGE_PIN A39 [get_ports {ddrb_72b_ck_c}]
set_property PACKAGE_PIN B39 [get_ports {ddrb_72b_ck_t}]
set_property PACKAGE_PIN A40 [get_ports {ddrb_72b_addr[1]}]
set_property PACKAGE_PIN B40 [get_ports {ddrb_72b_addr[2]}]
set_property PACKAGE_PIN D39 [get_ports {ddrb_72b_addr[8]}]
set_property PACKAGE_PIN E39 [get_ports {ddrb_72b_addr[7]}]
set_property PACKAGE_PIN D40 [get_ports {ddrb_72b_addr[5]}]
#set_property PACKAGE_PIN E40 [get_ports? {ddrb_72b_alert}]
set_property PACKAGE_PIN F35 [get_ports {ddrb_72b_addr[11]}]
set_property PACKAGE_PIN F34 [get_ports {ddrb_72b_addr[13]}]
set_property PACKAGE_PIN G34 [get_ports {ddrb_72b_cs_n[1]}]
#set_property PACKAGE_PIN H34 [get_ports? {ddrb_72b_addr[17]}]
set_property PACKAGE_PIN G36 [get_ports {ddrb_72b_rst_n}]
set_property PACKAGE_PIN H36 [get_ports {ddrb_72b_cke[0]}]
set_property PACKAGE_PIN J36 [get_ports {ddrb_72b_act_n}]
set_property PACKAGE_PIN J35 [get_ports {ddrb_72b_odt[1]}]
set_property PACKAGE_PIN F37 [get_ports {ddrb_72b_cke[1]}]
set_property PACKAGE_PIN G37 [get_ports {ddrb_72b_addr[9]}]
set_property PACKAGE_PIN H38 [get_ports {ddrb_72b_addr[12]}]
set_property PACKAGE_PIN H37 [get_ports {ddrb_72b_bg[0]}]
set_property PACKAGE_PIN E33 [get_ports {ddrb_72b_dq[26]}]
set_property PACKAGE_PIN F33 [get_ports {ddrb_72b_dq[24]}]
set_property PACKAGE_PIN E32 [get_ports {ddrb_72b_dq[27]}]
set_property PACKAGE_PIN F32 [get_ports {ddrb_72b_dq[25]}]
set_property PACKAGE_PIN H33 [get_ports {ddrb_72b_dqs_c[3]}]
set_property PACKAGE_PIN J33 [get_ports {ddrb_72b_dqs_t[3]}]

set_property PACKAGE_PIN G32 [get_ports {ddrb_72b_dq[31]}]
set_property PACKAGE_PIN H32 [get_ports {ddrb_72b_dq[29]}]
set_property PACKAGE_PIN G31 [get_ports {ddrb_72b_dq[30]}]
set_property PACKAGE_PIN H31 [get_ports {ddrb_72b_dq[28]}]
set_property PACKAGE_PIN G30 [get_ports {ddrb_72b_dm_dbi_n[3]}]
set_property PACKAGE_PIN K33 [get_ports {ddrb_72b_dq[9]}]
set_property PACKAGE_PIN L33 [get_ports {ddrb_72b_dq[8]}]
set_property PACKAGE_PIN J31 [get_ports {ddrb_72b_dq[11]}]
set_property PACKAGE_PIN K31 [get_ports {ddrb_72b_dq[10]}]
set_property PACKAGE_PIN J30 [get_ports {ddrb_72b_dqs_c[1]}]
set_property PACKAGE_PIN K30 [get_ports {ddrb_72b_dqs_t[1]}]
set_property PACKAGE_PIN L30 [get_ports {ddrb_72b_dq[12]}]
set_property PACKAGE_PIN M30 [get_ports {ddrb_72b_dq[13]}]
set_property PACKAGE_PIN K32 [get_ports {ddrb_72b_dq[14]}]
set_property PACKAGE_PIN L32 [get_ports {ddrb_72b_dq[15]}]
set_property PACKAGE_PIN M31 [get_ports {ddrb_72b_dm_dbi_n[1]}]
set_property PACKAGE_PIN N33 [get_ports {ddrb_72b_dq[3]}]
set_property PACKAGE_PIN N32 [get_ports {ddrb_72b_dq[2]}]
set_property PACKAGE_PIN N31 [get_ports {ddrb_72b_dq[0]}]
set_property PACKAGE_PIN P31 [get_ports {ddrb_72b_dq[1]}]
set_property PACKAGE_PIN L34 [get_ports {ddrb_72b_dqs_c[0]}]
set_property PACKAGE_PIN M34 [get_ports {ddrb_72b_dqs_t[0]}]
set_property PACKAGE_PIN N34 [get_ports {ddrb_72b_dq[7]}]
set_property PACKAGE_PIN P34 [get_ports {ddrb_72b_dq[6]}]
set_property PACKAGE_PIN R32 [get_ports {ddrb_72b_dq[5]}]
set_property PACKAGE_PIN R31 [get_ports {ddrb_72b_dq[4]}]
set_property PACKAGE_PIN R30 [get_ports {ddrb_72b_dm_dbi_n[0]}]
set_property PACKAGE_PIN T30 [get_ports {ddrb_72b_dq[56]}]
set_property PACKAGE_PIN U30 [get_ports {ddrb_72b_dq[57]}]
set_property PACKAGE_PIN U31 [get_ports {ddrb_72b_dq[58]}]
set_property PACKAGE_PIN V31 [get_ports {ddrb_72b_dq[59]}]
set_property PACKAGE_PIN V33 [get_ports {ddrb_72b_dqs_c[7]}]
set_property PACKAGE_PIN V32 [get_ports {ddrb_72b_dqs_t[7]}]

set_property PACKAGE_PIN T32 [get_ports {ddrb_72b_dq[60]}]
set_property PACKAGE_PIN U32 [get_ports {ddrb_72b_dq[61]}]
set_property PACKAGE_PIN R33 [get_ports {ddrb_72b_dq[62]}]
set_property PACKAGE_PIN T33 [get_ports {ddrb_72b_dq[63]}]
set_property PACKAGE_PIN U34 [get_ports {ddrb_72b_dm_dbi_n[7]}]
#DDR_c
set_property PACKAGE_PIN AM14 [get_ports {ddrc_72b_dq[57]}]
set_property PACKAGE_PIN AL14 [get_ports {ddrc_72b_dq[56]}]
set_property PACKAGE_PIN AM15 [get_ports {ddrc_72b_dq[58]}]
set_property PACKAGE_PIN AL15 [get_ports {ddrc_72b_dq[59]}]
set_property PACKAGE_PIN AR13 [get_ports {ddrc_72b_dqs_c[7]}]
set_property PACKAGE_PIN AP13 [get_ports {ddrc_72b_dqs_t[7]}]
set_property PACKAGE_PIN AN13 [get_ports {ddrc_72b_dq[62]}]
set_property PACKAGE_PIN AN14 [get_ports {ddrc_72b_dq[63]}]
set_property PACKAGE_PIN AP14 [get_ports {ddrc_72b_dq[61]}]
set_property PACKAGE_PIN AP15 [get_ports {ddrc_72b_dq[60]}]
set_property PACKAGE_PIN AR16 [get_ports {ddrc_72b_dm_dbi_n[7]}]
set_property PACKAGE_PIN AV16 [get_ports {ddrc_72b_dq[49]}]
set_property PACKAGE_PIN AU16 [get_ports {ddrc_72b_dq[48]}]
set_property PACKAGE_PIN AU15 [get_ports {ddrc_72b_dq[50]}]
set_property PACKAGE_PIN AT15 [get_ports {ddrc_72b_dq[51]}]
set_property PACKAGE_PIN AV14 [get_ports {ddrc_72b_dqs_c[6]}]
set_property PACKAGE_PIN AU14 [get_ports {ddrc_72b_dqs_t[6]}]
set_property PACKAGE_PIN AV13 [get_ports {ddrc_72b_dq[54]}]
set_property PACKAGE_PIN AU13 [get_ports {ddrc_72b_dq[55]}]
set_property PACKAGE_PIN AW15 [get_ports {ddrc_72b_dq[52]}]
set_property PACKAGE_PIN AW16 [get_ports {ddrc_72b_dq[53]}]
set_property PACKAGE_PIN AW14 [get_ports {ddrc_72b_dm_dbi_n[6]}]
set_property PACKAGE_PIN BA13 [get_ports {ddrc_72b_dq[40]}]
set_property PACKAGE_PIN AY13 [get_ports {ddrc_72b_dq[42]}]
set_property PACKAGE_PIN BA14 [get_ports {ddrc_72b_dq[41]}]
set_property PACKAGE_PIN BA15 [get_ports {ddrc_72b_dq[43]}]
set_property PACKAGE_PIN BB14 [get_ports {ddrc_72b_dqs_c[5]}]

set_property PACKAGE_PIN BB15 [get_ports {ddrc_72b_dqs_t[5]}]
set_property PACKAGE_PIN AY15 [get_ports {ddrc_72b_dq[45]}]
set_property PACKAGE_PIN AY16 [get_ports {ddrc_72b_dq[44]}]
set_property PACKAGE_PIN AY11 [get_ports {ddrc_72b_dq[46]}]
set_property PACKAGE_PIN AY12 [get_ports {ddrc_72b_dq[47]}]
set_property PACKAGE_PIN BA12 [get_ports {ddrc_72b_dm_dbi_n[5]}]
set_property PACKAGE_PIN BC13 [get_ports {ddrc_72b_dq[34]}]
set_property PACKAGE_PIN BC14 [get_ports {ddrc_72b_dq[35]}]
set_property PACKAGE_PIN BD14 [get_ports {ddrc_72b_dq[33]}]
set_property PACKAGE_PIN BD15 [get_ports {ddrc_72b_dq[32]}]
set_property PACKAGE_PIN BE13 [get_ports {ddrc_72b_dqs_c[4]}]
set_property PACKAGE_PIN BD13 [get_ports {ddrc_72b_dqs_t[4]}]
set_property PACKAGE_PIN BE16 [get_ports {ddrc_72b_dq[36]}]
set_property PACKAGE_PIN BD16 [get_ports {ddrc_72b_dq[37]}]
set_property PACKAGE_PIN BF15 [get_ports {ddrc_72b_dq[39]}]
set_property PACKAGE_PIN BE15 [get_ports {ddrc_72b_dq[38]}]
set_property PACKAGE_PIN BF14 [get_ports {ddrc_72b_dm_dbi_n[4]}]
set_property PACKAGE_PIN AM20 [get_ports {ddrc_72b_dq[64]}]
set_property PACKAGE_PIN AL20 [get_ports {ddrc_72b_dq[65]}]
set_property PACKAGE_PIN AM19 [get_ports {ddrc_72b_dq[66]}]
set_property PACKAGE_PIN AL19 [get_ports {ddrc_72b_dq[67]}]
set_property PACKAGE_PIN AM17 [get_ports {ddrc_72b_dqs_c[8]}]
set_property PACKAGE_PIN AL17 [get_ports {ddrc_72b_dqs_t[8]}]
set_property PACKAGE_PIN AN16 [get_ports {ddrc_72b_dq[71]}]
set_property PACKAGE_PIN AM16 [get_ports {ddrc_72b_dq[69]}]
set_property PACKAGE_PIN AP19 [get_ports {ddrc_72b_dq[70]}]
set_property PACKAGE_PIN AN19 [get_ports {ddrc_72b_dq[68]}]
set_property PACKAGE_PIN AN18 [get_ports {ddrc_72b_dm_dbi_n[8]}]
set_property PACKAGE_PIN AR20 [get_ports {ddrc_72b_addr[14]}]
set_property PACKAGE_PIN AP20 [get_ports {ddrc_72b_addr[13]}]
set_property PACKAGE_PIN AR18 [get_ports {ddrc_72b_par}]
#set_property PACKAGE_PIN AP18 [get_ports {ddrc_72b_addr[17]}]
set_property PACKAGE_PIN AT17 [get_ports {ddrc_72b_addr[15]}]

set_property PACKAGE_PIN AR17 [get_ports {ddrc_72b_ba[1]}]
set_property PACKAGE_PIN AU17 [get_ports {ddrc_72b_cs_n[1]}]
set_property PACKAGE_PIN AT18 [get_ports {ddrc_72b_odt[1]}]
set_property PACKAGE_PIN AU20 [get_ports {ddrc_72b_addr[10]}]
set_property PACKAGE_PIN AT20 [get_ports {ddrc_72b_ba[0]}]
set_property PACKAGE_PIN AU19 [get_ports {ddrc_72b_addr[0]}]
set_property PACKAGE_PIN AT19 [get_ports {ddrc_72b_odt[0]}]
set_property PACKAGE_PIN AW19 [get_ports {ddrc_100m_ref_clk_n}]
set_property PACKAGE_PIN AV19 [get_ports {ddrc_100m_ref_clk_p}]
set_property PACKAGE_PIN AW18 [get_ports {ddrc_72b_rst_n}]
set_property PACKAGE_PIN AV18 [get_ports {ddrc_72b_addr[16]}]
set_property PACKAGE_PIN AW21 [get_ports {ddrc_72b_ck_c}]
set_property PACKAGE_PIN AV21 [get_ports {ddrc_72b_ck_t}]
set_property PACKAGE_PIN AY20 [get_ports {ddrc_72b_cke[0]}]
set_property PACKAGE_PIN AW20 [get_ports {ddrc_72b_cke[1]}]
set_property PACKAGE_PIN BA18 [get_ports {ddrc_72b_addr[4]}]
set_property PACKAGE_PIN AY18 [get_ports {ddrc_72b_addr[7]}]
set_property PACKAGE_PIN BA17 [get_ports {ddrc_72b_addr[2]}]
set_property PACKAGE_PIN AY17 [get_ports {ddrc_72b_cs_n[0]}]
set_property PACKAGE_PIN BC18 [get_ports {ddrc_72b_bg[1]}]
set_property PACKAGE_PIN BB19 [get_ports {ddrc_72b_act_n}]
set_property PACKAGE_PIN BC17 [get_ports {ddrc_72b_addr[6]}]
set_property PACKAGE_PIN BB17 [get_ports {ddrc_72b_addr[1]}]
#set_property PACKAGE_PIN BD19 [get_ports {ddrc_72b_alert}]
set_property PACKAGE_PIN BC19 [get_ports {ddrc_72b_bg[0]}]
set_property PACKAGE_PIN BE18 [get_ports {ddrc_72b_addr[11]}]
set_property PACKAGE_PIN BD18 [get_ports {ddrc_72b_addr[12]}]
set_property PACKAGE_PIN BF18 [get_ports {ddrc_72b_addr[8]}]
set_property PACKAGE_PIN BF19 [get_ports {ddrc_72b_addr[9]}]
set_property PACKAGE_PIN BF17 [get_ports {ddrc_72b_addr[3]}]
set_property PACKAGE_PIN BE17 [get_ports {ddrc_72b_addr[5]}]
set_property PACKAGE_PIN AL28 [get_ports {ddrc_72b_dq[1]}]
set_property PACKAGE_PIN AL27 [get_ports {ddrc_72b_dq[0]}]

set_property PACKAGE_PIN AN27 [get_ports {ddrc_72b_dq[2]}]
set_property PACKAGE_PIN AM27 [get_ports {ddrc_72b_dq[3]}]
set_property PACKAGE_PIN AN26 [get_ports {ddrc_72b_dqs_c[0]}]
set_property PACKAGE_PIN AM26 [get_ports {ddrc_72b_dqs_t[0]}]
set_property PACKAGE_PIN AM25 [get_ports {ddrc_72b_dq[5]}]
set_property PACKAGE_PIN AL25 [get_ports {ddrc_72b_dq[4]}]
set_property PACKAGE_PIN AP28 [get_ports {ddrc_72b_dq[7]}]
set_property PACKAGE_PIN AN28 [get_ports {ddrc_72b_dq[6]}]
set_property PACKAGE_PIN AP25 [get_ports {ddrc_72b_dm_dbi_n[0]}]
set_property PACKAGE_PIN AT28 [get_ports {ddrc_72b_dq[26]}]
set_property PACKAGE_PIN AR28 [get_ports {ddrc_72b_dq[24]}]
set_property PACKAGE_PIN AT27 [get_ports {ddrc_72b_dq[27]}]
set_property PACKAGE_PIN AR27 [get_ports {ddrc_72b_dq[25]}]
set_property PACKAGE_PIN AT25 [get_ports {ddrc_72b_dqs_c[3]}]
set_property PACKAGE_PIN AR25 [get_ports {ddrc_72b_dqs_t[3]}]
set_property PACKAGE_PIN AU27 [get_ports {ddrc_72b_dq[29]}]
set_property PACKAGE_PIN AU26 [get_ports {ddrc_72b_dq[31]}]
set_property PACKAGE_PIN AV28 [get_ports {ddrc_72b_dq[30]}]
set_property PACKAGE_PIN AV27 [get_ports {ddrc_72b_dq[28]}]
set_property PACKAGE_PIN AV26 [get_ports {ddrc_72b_dm_dbi_n[3]}]
set_property PACKAGE_PIN AY28 [get_ports {ddrc_72b_dq[10]}]
set_property PACKAGE_PIN AW28 [get_ports {ddrc_72b_dq[11]}]
set_property PACKAGE_PIN AY27 [get_ports {ddrc_72b_dq[9]}]
set_property PACKAGE_PIN AY26 [get_ports {ddrc_72b_dq[8]}]
set_property PACKAGE_PIN AY25 [get_ports {ddrc_72b_dqs_c[1]}]
set_property PACKAGE_PIN AW25 [get_ports {ddrc_72b_dqs_t[1]}]
set_property PACKAGE_PIN BA28 [get_ports {ddrc_72b_dq[14]}]
set_property PACKAGE_PIN BA27 [get_ports {ddrc_72b_dq[15]}]
set_property PACKAGE_PIN BB27 [get_ports {ddrc_72b_dq[13]}]
set_property PACKAGE_PIN BB26 [get_ports {ddrc_72b_dq[12]}]
set_property PACKAGE_PIN BA25 [get_ports {ddrc_72b_dm_dbi_n[1]}]
set_property PACKAGE_PIN BC27 [get_ports {ddrc_72b_dq[17]}]
set_property PACKAGE_PIN BC26 [get_ports {ddrc_72b_dq[16]}]

set_property PACKAGE_PIN BF25 [get_ports {ddrc_72b_dq[18]}]
set_property PACKAGE_PIN BE25 [get_ports {ddrc_72b_dq[19]}]
set_property PACKAGE_PIN BE26 [get_ports {ddrc_72b_dqs_c[2]}]
set_property PACKAGE_PIN BD26 [get_ports {ddrc_72b_dqs_t[2]}]
set_property PACKAGE_PIN BE28 [get_ports {ddrc_72b_dq[21]}]
set_property PACKAGE_PIN BD28 [get_ports {ddrc_72b_dq[20]}]
set_property PACKAGE_PIN BF27 [get_ports {ddrc_72b_dq[22]}]
set_property PACKAGE_PIN BE27 [get_ports {ddrc_72b_dq[23]}]
set_property PACKAGE_PIN BF28 [get_ports {ddrc_72b_dm_dbi_n[2]}]
#DDR_d
set_property PACKAGE_PIN A25 [get_ports {ddrd_72b_dq[17]}]
set_property PACKAGE_PIN B25 [get_ports {ddrd_72b_dq[16]}]
set_property PACKAGE_PIN A24 [get_ports {ddrd_72b_dq[19]}]
set_property PACKAGE_PIN B24 [get_ports {ddrd_72b_dq[18]}]
set_property PACKAGE_PIN A22 [get_ports {ddrd_72b_dqs_c[2]}]
set_property PACKAGE_PIN A23 [get_ports {ddrd_72b_dqs_t[2]}]
set_property PACKAGE_PIN B26 [get_ports {ddrd_72b_dq[21]}]
set_property PACKAGE_PIN C26 [get_ports {ddrd_72b_dq[20]}]
set_property PACKAGE_PIN C23 [get_ports {ddrd_72b_dq[23]}]
set_property PACKAGE_PIN C24 [get_ports {ddrd_72b_dq[22]}]
set_property PACKAGE_PIN C22 [get_ports {ddrd_72b_dm_dbi_n[2]}]
set_property PACKAGE_PIN D25 [get_ports {ddrd_72b_dq[10]}]
set_property PACKAGE_PIN E25 [get_ports {ddrd_72b_dq[11]}]
set_property PACKAGE_PIN D23 [get_ports {ddrd_72b_dq[9]}]
set_property PACKAGE_PIN D24 [get_ports {ddrd_72b_dq[8]}]
set_property PACKAGE_PIN E22 [get_ports {ddrd_72b_dqs_c[1]}]
set_property PACKAGE_PIN E23 [get_ports {ddrd_72b_dqs_t[1]}]
set_property PACKAGE_PIN F22 [get_ports {ddrd_72b_dq[12]}]
set_property PACKAGE_PIN G22 [get_ports {ddrd_72b_dq[13]}]
set_property PACKAGE_PIN F23 [get_ports {ddrd_72b_dq[14]}]
set_property PACKAGE_PIN F24 [get_ports {ddrd_72b_dq[15]}]
set_property PACKAGE_PIN G25 [get_ports {ddrd_72b_dm_dbi_n[1]}]
set_property PACKAGE_PIN H24 [get_ports {ddrd_72b_dq[64]}]

set_property PACKAGE_PIN J24 [get_ports {ddrd_72b_dq[65]}]
set_property PACKAGE_PIN H23 [get_ports {ddrd_72b_dq[66]}]
set_property PACKAGE_PIN J23 [get_ports {ddrd_72b_dq[67]}]
set_property PACKAGE_PIN J25 [get_ports {ddrd_72b_dqs_c[8]}]
set_property PACKAGE_PIN K25 [get_ports {ddrd_72b_dqs_t[8]}]
set_property PACKAGE_PIN K23 [get_ports {ddrd_72b_dq[71]}]
set_property PACKAGE_PIN L23 [get_ports {ddrd_72b_dq[68]}]
set_property PACKAGE_PIN K22 [get_ports {ddrd_72b_dq[69]}]
set_property PACKAGE_PIN L22 [get_ports {ddrd_72b_dq[70]}]
set_property PACKAGE_PIN L25 [get_ports {ddrd_72b_dm_dbi_n[8]}]
set_property PACKAGE_PIN P25 [get_ports {ddrd_72b_dq[1]}]
set_property PACKAGE_PIN R25 [get_ports {ddrd_72b_dq[0]}]
set_property PACKAGE_PIN M24 [get_ports {ddrd_72b_dq[3]}]
set_property PACKAGE_PIN M25 [get_ports {ddrd_72b_dq[2]}]
set_property PACKAGE_PIN N24 [get_ports {ddrd_72b_dqs_c[0]}]
set_property PACKAGE_PIN P24 [get_ports {ddrd_72b_dqs_t[0]}]
set_property PACKAGE_PIN N23 [get_ports {ddrd_72b_dq[7]}]
set_property PACKAGE_PIN P23 [get_ports {ddrd_72b_dq[5]}]
set_property PACKAGE_PIN M22 [get_ports {ddrd_72b_dq[6]}]
set_property PACKAGE_PIN N22 [get_ports {ddrd_72b_dq[4]}]
set_property PACKAGE_PIN R21 [get_ports {ddrd_72b_dm_dbi_n[0]}]
set_property PACKAGE_PIN A20 [get_ports {ddrd_72b_dq[27]}]
set_property PACKAGE_PIN B20 [get_ports {ddrd_72b_dq[26]}]
set_property PACKAGE_PIN A19 [get_ports {ddrd_72b_dq[25]}]
set_property PACKAGE_PIN B19 [get_ports {ddrd_72b_dq[24]}]
set_property PACKAGE_PIN C18 [get_ports {ddrd_72b_dqs_c[3]}]
set_property PACKAGE_PIN D18 [get_ports {ddrd_72b_dqs_t[3]}]
set_property PACKAGE_PIN B21 [get_ports {ddrd_72b_dq[29]}]
set_property PACKAGE_PIN C21 [get_ports {ddrd_72b_dq[28]}]
set_property PACKAGE_PIN D20 [get_ports {ddrd_72b_dq[31]}]
set_property PACKAGE_PIN D21 [get_ports {ddrd_72b_dq[30]}]
set_property PACKAGE_PIN D19 [get_ports {ddrd_72b_dm_dbi_n[3]}]
set_property PACKAGE_PIN F17 [get_ports {ddrd_72b_addr[16]}]

set_property PACKAGE_PIN F18 [get_ports {ddrd_72b_par}]
set_property PACKAGE_PIN E20 [get_ports {ddrd_72b_addr[8]}]
set_property PACKAGE_PIN E21 [get_ports {ddrd_72b_addr[9]}]
set_property PACKAGE_PIN E17 [get_ports {ddrd_72b_addr[0]}]
set_property PACKAGE_PIN E18 [get_ports {ddrd_72b_ba[1]}]
set_property PACKAGE_PIN F19 [get_ports {ddrd_72b_addr[12]}]
set_property PACKAGE_PIN F20 [get_ports {ddrd_72b_addr[5]}]
set_property PACKAGE_PIN G19 [get_ports {ddrd_72b_addr[4]}]
set_property PACKAGE_PIN G20 [get_ports {ddrd_72b_bg[0]}]
set_property PACKAGE_PIN H18 [get_ports {ddrd_72b_addr[13]}]
set_property PACKAGE_PIN H19 [get_ports {ddrd_72b_addr[14]}]
set_property PACKAGE_PIN J19 [get_ports {ddrd_100m_ref_clk_n}]
set_property PACKAGE_PIN J20 [get_ports {ddrd_100m_ref_clk_p}]
set_property PACKAGE_PIN J18 [get_ports {ddrd_72b_addr[6]}]
set_property PACKAGE_PIN K18 [get_ports {ddrd_72b_addr[10]}]
set_property PACKAGE_PIN H21 [get_ports {ddrd_72b_ck_c}]
set_property PACKAGE_PIN J21 [get_ports {ddrd_72b_ck_t}]
set_property PACKAGE_PIN K20 [get_ports {ddrd_72b_addr[11]}]
set_property PACKAGE_PIN L20 [get_ports {ddrd_72b_addr[1]}]
set_property PACKAGE_PIN L18 [get_ports {ddrd_72b_addr[15]}]
set_property PACKAGE_PIN L19 [get_ports {ddrd_72b_addr[3]}]
set_property PACKAGE_PIN K17 [get_ports {ddrd_72b_cs_n[0]}]
set_property PACKAGE_PIN L17 [get_ports {ddrd_72b_odt[1]}]
set_property PACKAGE_PIN M21 [get_ports {ddrd_72b_bg[1]}]
set_property PACKAGE_PIN N21 [get_ports {ddrd_72b_cke[0]}]
set_property PACKAGE_PIN P20 [get_ports {ddrd_72b_rst_n}]
set_property PACKAGE_PIN R20 [get_ports {ddrd_72b_cke[1]}]
set_property PACKAGE_PIN N19 [get_ports {ddrd_72b_act_n}]
#set_property PACKAGE_PIN P19 [get_ports {ddrd_72b_alert}]
#set_property PACKAGE_PIN M19 [get_ports {ddrd_72b_addr[17]}]
set_property PACKAGE_PIN M20 [get_ports {ddrd_72b_addr[2]}]
set_property PACKAGE_PIN N18 [get_ports {ddrd_72b_addr[7]}]
set_property PACKAGE_PIN P18 [get_ports {ddrd_72b_odt[0]}]

set_property PACKAGE_PIN M17 [get_ports {ddrd_72b_cs_n[1]}]
set_property PACKAGE_PIN N17 [get_ports {ddrd_72b_ba[0]}]
set_property PACKAGE_PIN A17 [get_ports {ddrd_72b_dq[32]}]
set_property PACKAGE_PIN B17 [get_ports {ddrd_72b_dq[35]}]
set_property PACKAGE_PIN B16 [get_ports {ddrd_72b_dq[33]}]
set_property PACKAGE_PIN C16 [get_ports {ddrd_72b_dq[34]}]
set_property PACKAGE_PIN A15 [get_ports {ddrd_72b_dqs_c[4]}]
set_property PACKAGE_PIN B15 [get_ports {ddrd_72b_dqs_t[4]}]
set_property PACKAGE_PIN A13 [get_ports {ddrd_72b_dq[38]}]
set_property PACKAGE_PIN A14 [get_ports {ddrd_72b_dq[39]}]
set_property PACKAGE_PIN B14 [get_ports {ddrd_72b_dq[37]}]
set_property PACKAGE_PIN C14 [get_ports {ddrd_72b_dq[36]}]
set_property PACKAGE_PIN D13 [get_ports {ddrd_72b_dm_dbi_n[4]}]
set_property PACKAGE_PIN D16 [get_ports {ddrd_72b_dq[42]}]
set_property PACKAGE_PIN E16 [get_ports {ddrd_72b_dq[43]}]
set_property PACKAGE_PIN D15 [get_ports {ddrd_72b_dq[40]}]
set_property PACKAGE_PIN E15 [get_ports {ddrd_72b_dq[41]}]
set_property PACKAGE_PIN G16 [get_ports {ddrd_72b_dqs_c[5]}]
set_property PACKAGE_PIN G17 [get_ports {ddrd_72b_dqs_t[5]}]
set_property PACKAGE_PIN E13 [get_ports {ddrd_72b_dq[47]}]
set_property PACKAGE_PIN F13 [get_ports {ddrd_72b_dq[46]}]
set_property PACKAGE_PIN F15 [get_ports {ddrd_72b_dq[45]}]
set_property PACKAGE_PIN G15 [get_ports {ddrd_72b_dq[44]}]
set_property PACKAGE_PIN G14 [get_ports {ddrd_72b_dm_dbi_n[5]}]
set_property PACKAGE_PIN J15 [get_ports {ddrd_72b_dq[51]}]
set_property PACKAGE_PIN J16 [get_ports {ddrd_72b_dq[50]}]
set_property PACKAGE_PIN H14 [get_ports {ddrd_72b_dq[48]}]
set_property PACKAGE_PIN J14 [get_ports {ddrd_72b_dq[49]}]
set_property PACKAGE_PIN H16 [get_ports {ddrd_72b_dqs_c[6]}]
set_property PACKAGE_PIN H17 [get_ports {ddrd_72b_dqs_t[6]}]
set_property PACKAGE_PIN H13 [get_ports {ddrd_72b_dq[53]}]
set_property PACKAGE_PIN J13 [get_ports {ddrd_72b_dq[52]}]
set_property PACKAGE_PIN K15 [get_ports {ddrd_72b_dq[55]}]

set_property PACKAGE_PIN K16 [get_ports {ddrd_72b_dq[54]}]
set_property PACKAGE_PIN L13 [get_ports {ddrd_72b_dm_dbi_n[6]}]
set_property PACKAGE_PIN M16 [get_ports {ddrd_72b_dq[58]}]
set_property PACKAGE_PIN N16 [get_ports {ddrd_72b_dq[59]}]
set_property PACKAGE_PIN L14 [get_ports {ddrd_72b_dq[56]}]
set_property PACKAGE_PIN M14 [get_ports {ddrd_72b_dq[57]}]
set_property PACKAGE_PIN P16 [get_ports {ddrd_72b_dqs_c[7]}]
set_property PACKAGE_PIN R16 [get_ports {ddrd_72b_dqs_t[7]}]
set_property PACKAGE_PIN P15 [get_ports {ddrd_72b_dq[61]}]
set_property PACKAGE_PIN R15 [get_ports {ddrd_72b_dq[60]}]
set_property PACKAGE_PIN N14 [get_ports {ddrd_72b_dq[63]}]
set_property PACKAGE_PIN P14 [get_ports {ddrd_72b_dq[62]}]
set_property PACKAGE_PIN P13 [get_ports {ddrd_72b_dm_dbi_n[7]}]
