# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.enableLutRouteBelPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.BramSDPPropagationFix 1
create_project -in_memory -part xcvu9p-flgb2104-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/centos/daniel/riffa/fpga/xilinx/huawei/huawei_pcie4/prj/Huawei_Gen4.cache/wt [current_project]
set_property parent.project_path /home/centos/daniel/riffa/fpga/xilinx/huawei/huawei_pcie4/prj/Huawei_Gen4.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog {
  /home/centos/daniel/riffa/fpga/riffa_hdl/functions.vh
  /home/centos/daniel/riffa/fpga/riffa_hdl/widths.vh
  /home/centos/daniel/riffa/fpga/riffa_hdl/riffa.vh
  /home/centos/daniel/riffa/fpga/riffa_hdl/types.vh
  /home/centos/daniel/riffa/fpga/riffa_hdl/ultrascale.vh
  /home/centos/daniel/riffa/fpga/riffa_hdl/trellis.vh
  /home/centos/daniel/riffa/fpga/riffa_hdl/tlp.vh
  /home/centos/daniel/riffa/fpga/riffa_hdl/schedules.vh
}
set_property is_global_include true [get_files /home/centos/daniel/riffa/fpga/riffa_hdl/functions.vh]
read_verilog -library xil_defaultlib {
  /home/centos/daniel/riffa/fpga/riffa_hdl/async_fifo.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/async_fifo_fwft.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/channel.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/channel_128.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/channel_32.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/channel_64.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/chnl_tester.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/counter.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/cross_domain_signal.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/demux.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/engine_layer.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/ff.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/fifo.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/fifo_packer_128.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/fifo_packer_32.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/fifo_packer_64.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/interrupt.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/interrupt_controller.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/mux.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/offset_flag_to_one_hot.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/offset_to_mask.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/one_hot_mux.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/pipeline.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/ram_1clk_1w_1r.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/ram_2clk_1w_1r.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/recv_credit_flow_ctrl.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/register.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/registers.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/reorder_queue.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/reorder_queue_input.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/reorder_queue_output.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/reset_controller.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/reset_extender.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/riffa.v
  /home/centos/daniel/riffa/fpga/xilinx/huawei/riffa_wrapper_vc709.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/rotate.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/rx_engine_classic.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/rx_engine_ultrascale.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/rx_port_128.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/rx_port_32.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/rx_port_64.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/rx_port_channel_gate.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/rx_port_reader.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/rx_port_requester_mux.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/rxc_engine_classic.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/rxc_engine_ultrascale.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/rxr_engine_classic.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/rxr_engine_ultrascale.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/scsdpram.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/sg_list_reader_128.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/sg_list_reader_32.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/sg_list_reader_64.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/sg_list_requester.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/shiftreg.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/sync_fifo.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/syncff.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_alignment_pipeline.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_data_fifo.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_data_pipeline.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_data_shift.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_engine.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_engine_classic.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_engine_selector.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_engine_ultrascale.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_hdr_fifo.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_multiplexer.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_multiplexer_128.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_multiplexer_32.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_multiplexer_64.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_port_128.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_port_32.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_port_64.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_port_buffer_128.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_port_buffer_32.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_port_buffer_64.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_port_channel_gate_128.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_port_channel_gate_32.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_port_channel_gate_64.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_port_monitor_128.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_port_monitor_32.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_port_monitor_64.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/tx_port_writer.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/txc_engine_classic.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/txc_engine_ultrascale.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/txr_engine_classic.v
  /home/centos/daniel/riffa/fpga/riffa_hdl/txr_engine_ultrascale.v
  /home/centos/daniel/riffa/fpga/xilinx/huawei/huawei_pcie4/hdl/Huawei_Gen4.v
}
read_ip -quiet /home/centos/daniel/riffa/fpga/xilinx/huawei/huawei_pcie4/ip/pcie4_uscale_plus_0/pcie4_uscale_plus_0.xci
set_property used_in_implementation false [get_files -all /home/centos/daniel/riffa/fpga/xilinx/huawei/huawei_pcie4/ip/pcie4_uscale_plus_0/ip_0/synth/pcie4_uscale_plus_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/centos/daniel/riffa/fpga/xilinx/huawei/huawei_pcie4/ip/pcie4_uscale_plus_0/ip_0/synth/pcie4_uscale_plus_0_gt.xdc]
set_property used_in_implementation false [get_files -all /home/centos/daniel/riffa/fpga/xilinx/huawei/huawei_pcie4/ip/pcie4_uscale_plus_0/pcie4_uscale_plus_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/centos/daniel/riffa/fpga/xilinx/huawei/huawei_pcie4/ip/pcie4_uscale_plus_0/synth/pcie4_uscale_plus_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/centos/daniel/riffa/fpga/xilinx/huawei/huawei_pcie4/ip/pcie4_uscale_plus_0/synth/pcie4_uscale_plus_0_late.xdc]
set_property used_in_implementation false [get_files -all /home/centos/daniel/riffa/fpga/xilinx/huawei/huawei_pcie4/ip/pcie4_uscale_plus_0/source/ip_pcie4_uscale_plus_x0y1.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Huawei_F100_Gen4 -part xcvu9p-flgb2104-2-i


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Huawei_F100_Gen4.dcp
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
